### ISSUE TITLE
How to upload the custom npz file to the specific folder

### ISSUE THREAD

**Issue by KevinWang676** [fidofetch/bark-app#1]
I wonder how to upload my npz file to the specific folder "bark/assets/prompts". I met this error. Thanks!

![image](https://user-images.githubusercontent.com/126712357/234422896-99d7425c-ab41-4382-b9b5-fe8317e79a81.png)

**Comment by fidofetch** [comment]
It is a folder that is contained in the repo. I built the app to run locally on your computer, I don't have much experience with notebooks.

**Comment by KevinWang676** [comment]
Got it, thank you!
